<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);MasterstrapSetup\**\*</DefaultItemExcludes>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Masterstrap</AssemblyName>
    <RootNamespace>Masterstrap</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StartupObject>Masterstrap.Program</StartupObject>
    <ApplicationIcon>Masterstrap.ico</ApplicationIcon>
    <Version>3.1.4</Version>
    <AssemblyVersion>3.1.4.0</AssemblyVersion>
    <FileVersion>3.1.4.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="crosshair\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
</Project>
